-- =============================================================================
-- H2 minimal schema (Postgres compatibility mode).
-- Loaded by Spring Boot SQL init when spring.profiles.active includes 'test-h2'.
--
-- This file is NOT a port of all Flyway migrations. It contains ONLY the tables
-- exercised by tests that extend H2IntegrationTestBase. To add coverage, add
-- the table here AND the corresponding seed (if any) in data.sql.
--
-- Limitations vs. Postgres: no jsonb operators, no pgcrypto, no plpgsql.
-- =============================================================================

-- The 'sim' schema is created by the JDBC URL INIT clause; this file assumes
-- it already exists.

-- ----- entidad ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sim.entidad (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(200)    NOT NULL UNIQUE,
    tipo            VARCHAR(40)     NOT NULL,
    descripcion     CLOB,
    contacto_nombre VARCHAR(150),
    contacto_email  VARCHAR(200),
    activa          BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_entidad_tipo CHECK (tipo IN (
        'UNIVERSIDAD', 'COLEGIO', 'EMPRESA', 'ONG', 'INSTITUTO', 'OTRO'
    ))
);
